### ISSUE TITLE
hello，theres nothing in ./model/,so show this error

### ISSUE THREAD

**Issue by jlk1997** [goddice/snerg-viewer-cpp#1]
![image](https://user-images.githubusercontent.com/56379549/224554221-20baabdd-4128-4998-b12f-b01ba12ba2ae.png)
after i input the second code

**Comment by goddice** [comment]
Are you able to access "https://storage.googleapis.com/snerg/750/lego/scene_params.json"?

**Comment by jlk1997** [comment]
yeah，i can access the website

**Comment by jlk1997** [comment]
![image](https://user-images.githubusercontent.com/56379549/226533758-42641ecd-c5d4-42c9-a36f-a1e102260835.png)
its my error

**Comment by jlk1997** [comment]
![image](https://user-images.githubusercontent.com/56379549/226534075-afdd5d1b-339c-4632-941c-17b7059f83b8.png)
after i paste the scene_params.json to the folder,the new error coming.
should i paster the same scene_params.json to each folder?

**Comment by jlk1997** [comment]
![image](https://user-images.githubusercontent.com/56379549/226536386-cb1f8a7b-d581-44f8-95c8-5d6b0b87905d.png)
i have build successfully,but there`s no result of program and don`t exist the ./build/app model/ folder
im in win11
